/*==============================================================================
 File: 04_Create_Indexes.sql - additional non-PK indexes
==============================================================================*/
USE hospital_analytics_db;

CREATE INDEX idx_department_type ON dim_department(department_type);
CREATE INDEX idx_department_status ON dim_department(department_status);
CREATE INDEX idx_insurance_company ON dim_insurance(company_name);
CREATE INDEX idx_insurance_type ON dim_insurance(insurance_type);
CREATE INDEX idx_payment_category ON dim_payment_mode(payment_category);
CREATE INDEX idx_payment_status ON dim_payment_mode(status);
CREATE INDEX idx_ward_department ON dim_ward(department_id);
CREATE INDEX idx_ward_type ON dim_ward(ward_type);
CREATE INDEX idx_bed_ward ON dim_bed(ward_id);
CREATE INDEX idx_bed_status ON dim_bed(bed_status);
CREATE INDEX idx_doctor_department ON dim_doctor(department_id);
CREATE INDEX idx_doctor_specialization ON dim_doctor(specialization);
CREATE INDEX idx_doctor_status ON dim_doctor(doctor_status);
CREATE INDEX idx_patient_name ON dim_patient(last_name,first_name);
CREATE INDEX idx_patient_city ON dim_patient(city);
CREATE INDEX idx_patient_status ON dim_patient(patient_status);
CREATE INDEX idx_diagnosis_category ON dim_diagnosis(diagnosis_category);
CREATE INDEX idx_medicine_category ON dim_medicine(medicine_category);
CREATE INDEX idx_medicine_status ON dim_medicine(medicine_status);
CREATE INDEX idx_lab_category ON dim_lab_test(test_category);
CREATE INDEX idx_lab_status ON dim_lab_test(test_status);
CREATE INDEX idx_date_year_month ON dim_date(year_number,month_number);

CREATE INDEX idx_apt_patient ON fact_appointments(patient_id);
CREATE INDEX idx_apt_doctor ON fact_appointments(doctor_id);
CREATE INDEX idx_apt_department ON fact_appointments(department_id);
CREATE INDEX idx_apt_date ON fact_appointments(date_key);
CREATE INDEX idx_apt_status ON fact_appointments(status);
CREATE INDEX idx_opd_patient ON fact_opd_visits(patient_id);
CREATE INDEX idx_opd_doctor ON fact_opd_visits(doctor_id);
CREATE INDEX idx_opd_department ON fact_opd_visits(department_id);
CREATE INDEX idx_opd_date ON fact_opd_visits(date_key);
CREATE INDEX idx_ipd_patient ON fact_ipd_admissions(patient_id);
CREATE INDEX idx_ipd_doctor ON fact_ipd_admissions(doctor_id);
CREATE INDEX idx_ipd_ward ON fact_ipd_admissions(ward_id);
CREATE INDEX idx_ipd_bed ON fact_ipd_admissions(bed_id);
CREATE INDEX idx_ipd_admission_date ON fact_ipd_admissions(admission_date_key);
CREATE INDEX idx_bill_patient ON fact_billing(patient_id);
CREATE INDEX idx_bill_date ON fact_billing(date_key);
CREATE INDEX idx_bill_status ON fact_billing(payment_status);
CREATE INDEX idx_claim_insurance ON fact_insurance_claims(insurance_id);
CREATE INDEX idx_claim_date ON fact_insurance_claims(claim_date_key);
CREATE INDEX idx_pharmacy_patient ON fact_pharmacy(patient_id);
CREATE INDEX idx_pharmacy_medicine ON fact_pharmacy(medicine_id);
CREATE INDEX idx_pharmacy_date ON fact_pharmacy(date_key);
CREATE INDEX idx_lab_patient ON fact_lab_orders(patient_id);
CREATE INDEX idx_lab_doctor ON fact_lab_orders(doctor_id);
CREATE INDEX idx_lab_test ON fact_lab_orders(test_id);
CREATE INDEX idx_lab_date ON fact_lab_orders(date_key);
CREATE INDEX idx_wait_patient ON fact_waiting_time(patient_id);
CREATE INDEX idx_wait_doctor ON fact_waiting_time(doctor_id);
CREATE INDEX idx_wait_department ON fact_waiting_time(department_id);
CREATE INDEX idx_wait_date ON fact_waiting_time(date_key);
CREATE INDEX idx_feedback_patient ON fact_patient_feedback(patient_id);
CREATE INDEX idx_feedback_doctor ON fact_patient_feedback(doctor_id);
CREATE INDEX idx_feedback_department ON fact_patient_feedback(department_id);
CREATE INDEX idx_feedback_date ON fact_patient_feedback(date_key);
CREATE INDEX idx_complaint_department ON fact_complaints(department_id);
CREATE INDEX idx_complaint_date ON fact_complaints(date_key);
CREATE INDEX idx_complaint_status ON fact_complaints(status);
CREATE INDEX idx_emergency_date ON fact_emergency(date_key);
CREATE INDEX idx_emergency_severity ON fact_emergency(emergency_severity);
CREATE INDEX idx_surgery_doctor ON fact_surgeries(doctor_id);
CREATE INDEX idx_surgery_date ON fact_surgeries(date_key);
CREATE INDEX idx_radiology_doctor ON fact_radiology(doctor_id);
CREATE INDEX idx_radiology_date ON fact_radiology(date_key);
CREATE INDEX idx_discharge_patient ON fact_discharge(patient_id);
CREATE INDEX idx_discharge_date ON fact_discharge(date_key);
CREATE INDEX idx_occupancy_bed ON fact_bed_occupancy(bed_id);
CREATE INDEX idx_occupancy_date ON fact_bed_occupancy(date_key);
CREATE INDEX idx_occupancy_patient ON fact_bed_occupancy(patient_id);

SELECT TABLE_NAME, INDEX_NAME, COLUMN_NAME FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() ORDER BY TABLE_NAME,INDEX_NAME,SEQ_IN_INDEX;
